name: Validate and Build IPTV

on:
  push:
    paths:
      - 'pais/*.m3u8'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run validator script
        run: python python/check_streams.py

      - name: Commit master.m3u8
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add master.m3u8 misc/dead.txt
          git commit -m "Update validated master.m3u8" || echo "No changes"
          git push
